re_kernel
AndroidPatch/kpm pull request #1
Opened 2024-05-03 15:53 UTC by lzghzr

2024-05-03 23:40 UTC, pomelohan requested changes
Good job bro, but it could be better if you add re_kernel kpm to CI queue.🌹

2024-05-04 01:19 UTC, lzghzr commented
> Good job bro, but it could be better if you add re_kernel kpm to CI queue.🌹

看了眼ci没有做成遍历目录，是出于什么特殊功能考虑吗

2024-05-05 00:53 UTC, pomelohan commented
> > Good job bro, but it could be better if you add re_kernel kpm to CI queue.🌹
> 
> 看了眼ci没有做成遍历目录，是出于什么特殊功能考虑吗

这部分不是我负责的，是 sekaiacg 大佬在做，可能是当时没考虑到这个场景，如果您方便的话可以把它切成遍历目录的写法吗，或者说不方便的话只用单一的也可以。

2024-05-05 04:32 UTC, lzghzr commented
> > > Good job bro, but it could be better if you add re_kernel kpm to CI queue.🌹
> > 
> > 
> > 看了眼ci没有做成遍历目录，是出于什么特殊功能考虑吗
> 
> 这部分不是我负责的，是 sekaiacg 大佬在做，可能是当时没考虑到这个场景，如果您方便的话可以把它切成遍历目录的写法吗，或者说不方便的话只用单一的也可以。

改成遍历src目录了

2024-05-05 04:47 UTC, pomelohan approved these changes

2024-05-05 04:48 UTC, merged